# Usa la imagen base de Ruby
FROM ruby:3.2

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo de código fuente
COPY Program.rb .

# Comando para ejecutar el script de Ruby
CMD ["ruby", "Program.rb"]